### ISSUE TITLE
Vidsrcto provider stopped working after change in keys.

### ISSUE THREAD

**Issue by mohitbkl** [streamflix-one/providers#2]
Ran into a bit of a snag with the Vidsrcto streaming provider. It seems the [KEY](https://github.com/streamflix-one/providers/blob/main/scrapers/vidsrcto.py#L171) have been updated recently, and now the streaming URLs aren't working without a referer.

Could you please update the new key with us? Also, it would be great if you could guide us on how to add a referer to the streaming URLs for Vidsrcto or maybe an implementation in the provider itself.

Also , Your discord invitation is not working , it would be great if your provide other ways for quick contact.

Thanks :)

**Comment by rdwxth** [comment]
Hey thanks for the heads up! I've updated the file with the new key. On the topic of adding a referrer to streaming urls,  easiest way to add a referrer to the streaming URL's when playing them is by using a [referrer proxy](https://github.com/Gratenes/m3u8CloudflareWorkerProxy).

You can use the referrer proxy like this:
```
https://m3u8.justchill.workers.dev/?url=https://pdrz.vid109d224.site/_v2-bknx/12a3c523f8105800ed8c394685aeeb0bc62eab5c1db1e3e90a027baea93ece832257df1a4b6125fcfa38c35da05dee86aad28d46d73fc4e9d4e5a53a5777f3d0749544f85c4ae80912c4b4bc6e4e7b146562d5740700379a9dc0e345d4e673cc7915f31f5035e349acb7704c/h/list;15a38634f803584ba8926411d7bee906856cab0654b5b8.m3u8&referer=e69975b881.nl
```


Also here's an Invite link to my Discord
https://discord.gg/TPTujh3ThF

**Comment by DHRUV-CODER** [comment]
tysm , this helps a lot.
