### ISSUE TITLE
🐞Bug : Missing requirements.txt 

### ISSUE THREAD

**Issue by d3vAdrian** [streamflix-one/providers#3]
![image](https://github.com/streamflix-one/providers/assets/115282353/0e252808-92d3-4a92-ac14-a2f22bea32b6)

**Comment by rdwxth** [comment]
Whoops, I forgot

Anyways you'll need Flask, Flask-CORS, Cloudscraper, and BeautifulSoup4. I'll upload the file next update though.

**Comment by deeeeone** [comment]
Added it now, and also fixed vidsrcme
